/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;

/**
 *
 * @author ADMIN
 */
public class GUI_HOME extends javax.swing.JFrame {

    /**
     * Creates new form GUI_HOMe
     */
    private GUI_NhapVe guiNhapVe; 
    private GUI_DatVe guiDatVe;
    private GUI_KhachHang guiKhachHang; 
    private GUI_HangVe guiHangVe; 
    private GUI_HangBay guiHangBay; 
    
    
    public GUI_HOME() {
        guiNhapVe = new GUI_NhapVe();
        guiDatVe = new GUI_DatVe(); 
        guiKhachHang = new GUI_KhachHang(); 
        guiHangVe = new GUI_HangVe(); 
        guiHangBay = new GUI_HangBay(); 
        
        initComponents();
        this.panelThayDoi.add(guiNhapVe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbChucVu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbTenNhanVien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNhapVe = new javax.swing.JButton();
        btnDatVe = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnHangVe = new javax.swing.JButton();
        btnHangBay = new javax.swing.JButton();
        panelThayDoi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(25, 145, 166));
        jPanel1.setPreferredSize(new java.awt.Dimension(379, 649));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\ChuongTrinhVeMayBay\\anh\\userTT.png")); // NOI18N

        jlbChucVu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jlbChucVu.setForeground(new java.awt.Color(255, 255, 255));
        jlbChucVu.setText("Quản Lý");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chức Vụ: ");

        jlbTenNhanVien.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jlbTenNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbTenNhanVien.setText("Trần Đỗ Đăng Khánh");

        jPanel2.setBackground(new java.awt.Color(25, 145, 166));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        btnNhapVe.setBackground(new java.awt.Color(25, 145, 166));
        btnNhapVe.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnNhapVe.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapVe.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\ChuongTrinhVeMayBay\\anh\\NhapVe.png")); // NOI18N
        btnNhapVe.setText("    Nhập Vé");
        btnNhapVe.setBorder(null);
        btnNhapVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapVeActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhapVe);

        btnDatVe.setBackground(new java.awt.Color(25, 145, 166));
        btnDatVe.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDatVe.setForeground(new java.awt.Color(255, 255, 255));
        btnDatVe.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\ChuongTrinhVeMayBay\\anh\\DatVe.png")); // NOI18N
        btnDatVe.setText("    Đặt Vé");
        btnDatVe.setBorder(null);
        btnDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatVeActionPerformed(evt);
            }
        });
        jPanel2.add(btnDatVe);

        btnKhachHang.setBackground(new java.awt.Color(25, 145, 166));
        btnKhachHang.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\ChuongTrinhVeMayBay\\anh\\KhachHang.png")); // NOI18N
        btnKhachHang.setText("    Khách Hàng");
        btnKhachHang.setBorder(null);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jPanel2.add(btnKhachHang);

        btnHangVe.setBackground(new java.awt.Color(25, 145, 166));
        btnHangVe.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnHangVe.setForeground(new java.awt.Color(255, 255, 255));
        btnHangVe.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\ChuongTrinhVeMayBay\\anh\\HangVe.png")); // NOI18N
        btnHangVe.setText("    Hạng Vé");
        btnHangVe.setBorder(null);
        btnHangVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangVeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHangVe);

        btnHangBay.setBackground(new java.awt.Color(25, 145, 166));
        btnHangBay.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnHangBay.setForeground(new java.awt.Color(255, 255, 255));
        btnHangBay.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\ChuongTrinhVeMayBay\\anh\\HangBay.png")); // NOI18N
        btnHangBay.setText("    Hãng Bay");
        btnHangBay.setBorder(null);
        btnHangBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangBayActionPerformed(evt);
            }
        });
        jPanel2.add(btnHangBay);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTenNhanVien)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbChucVu)))
                .addContainerGap(132, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jlbTenNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlbChucVu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
        );

        panelThayDoi.setBackground(new java.awt.Color(255, 255, 255));
        panelThayDoi.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));
        jPanel3.setPreferredSize(new java.awt.Dimension(659, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setText("HỆ THỐNG BÁN VÉ MÁY BAY");
        jPanel3.add(jLabel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelThayDoi, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelThayDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapVeActionPerformed
        thayDoiPanelChinh(guiNhapVe, btnNhapVe);
    }//GEN-LAST:event_btnNhapVeActionPerformed

    private void btnDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatVeActionPerformed
       thayDoiPanelChinh(guiDatVe, btnDatVe);
    }//GEN-LAST:event_btnDatVeActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        thayDoiPanelChinh(guiKhachHang, btnKhachHang);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnHangVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangVeActionPerformed
        thayDoiPanelChinh(guiHangVe, btnHangVe);
    }//GEN-LAST:event_btnHangVeActionPerformed

    private void btnHangBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangBayActionPerformed
        thayDoiPanelChinh(guiHangBay, btnHangBay);
    }//GEN-LAST:event_btnHangBayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_HOME().setVisible(true);
               
            }
        });
    }
    
    public void thayDoiPanelChinh(JComponent component, JButton btn) {
        btn.setSelected(true);
        this.panelThayDoi.removeAll();
        this.panelThayDoi.repaint();
        this.panelThayDoi.revalidate();

        this.panelThayDoi.add(component);
        this.panelThayDoi.repaint();
        this.panelThayDoi.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatVe;
    private javax.swing.JButton btnHangBay;
    private javax.swing.JButton btnHangVe;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhapVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbChucVu;
    private javax.swing.JLabel jlbTenNhanVien;
    private javax.swing.JPanel panelThayDoi;
    // End of variables declaration//GEN-END:variables
}
